import { News, NewsType } from './models/news';
import { createId } from '../../shared/types/branded-types';

export const newsData: Array<News> = [
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Update,
    title: 'BIG NEWS',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Ipsus',
    illustrationSrc: 'assets/2026-season/players/BB-Nastie.png',
    publisher: 'Someone',
    publishedOn: new Date(),
  }),
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Update,
    title: 'BIG NEWS',
    subtitle: 'This is a big big news',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Ipsus',
    illustrationSrc: 'assets/2026-season/players/FV-Abuzah.png',
    publisher: 'Someone',
    publishedOn: new Date('2026-03-11'),
  }),
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Schedule,
    title: 'BIG NEWS',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Ipsus',
    illustrationSrc: 'assets/2026-season/players/PGM-Sib.png',
    publisher: 'Someone',
    publishedOn: new Date('2026-04-11'),
  }),
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Schedule,
    title: 'BIG NEWS',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Lorem Ipsum Dolere It Ipsus',
    illustrationSrc: 'assets/2026-season/players/PGM-Envoy.png',
    publisher: 'Someone',
    publishedOn: new Date('2026-01-01'),
  }),
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Results,
    title: 'BIG NEWS',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Lorem Ipsum Dolere It Ipsus',
    illustrationSrc: 'assets/2026-season/players/PGM-Neptune.png',
    publisher: 'Someone',
    publishedOn: new Date('2025-08-02'),
  }),
  News.create({
    id: createId(crypto.randomUUID(), 'NewsId'),
    type: NewsType.Results,
    title: 'BIG NEWS',
    content: 'Lorem Ipsum Dolere It Ipsus',
    summary: 'Lorem Ipsum Dolere It Ipsus',
    illustrationSrc: 'assets/Logo_Placeholder.png',
    publisher: 'Someone',
    publishedOn: new Date('2023-07-05'),
  }),
];
