export enum LinkFlavourText {
  CompleteCoverage = 'Complete coverage',
  ContinueReading = 'Continue reading',
  ContinueYourJourney = 'Continue your journey',
  DiveDeeper = 'Dive deeper',
  DiscoverMore = 'Discover more',
  ExploreArticle = 'Explore article',
  ExploreTheStory = 'Explore the story',
  FindOutMore = 'Find out more',
  FullStory = 'Full story',
  GetTheFullPicture = 'Get the full picture',
  KeepReading = 'Keep reading',
  LearnMore = 'Learn more',
  LearnTheFacts = 'Learn the facts',
  MoreInfo = 'More info',
  ReadMore = 'Read more',
  ReadTheArticle = 'Read the article',
  SeeDetails = 'See details',
  SeeWhatsNext = 'See what’s next',
  UnlockFullStory = 'Unlock full story',
  ViewFullContent = 'View full content',
  ViewTeamRoster = 'View team roster',
}
