export enum LinkFlavourTextEnum {
  ReadMore = 'Read more',
  ContinueReading = 'Continue reading',
  FullStory = 'Full story',
  LearnMore = 'Learn more',
  SeeDetails = 'See details',
  MoreInfo = 'More info',
  ReadTheArticle = 'Read the article',
  ViewFullContent = 'View full content',
  ExploreArticle = 'Explore article',
  CompleteCoverage = 'Complete coverage',
  DiveDeeper = 'Dive deeper',
  KeepReading = 'Keep reading',
  DiscoverMore = 'Discover more',
  FindOutMore = 'Find out more',
  UnlockFullStory = 'Unlock full story',
  SeeWhatsNext = 'See what’s next',
  ContinueYourJourney = 'Continue your journey',
  GetTheFullPicture = 'Get the full picture',
  ExploreTheStory = 'Explore the story',
  LearnTheFacts = 'Learn the facts',
}
